#!/usr/bin/env bash

set -e

RODENT_ABS_PATH=$(dirname "$(readlink -f "$0")")

. "$RODENT_ABS_PATH/../env/settings"

prog="${0##*/}"

localdir="$PWD"

[[ -z "$RODENT_DISABLE_REVERSE_SEARCH" ]] || {
  echo "invesr"
  pushd .
  while [[ "$PWD" != '/' ]]
  do
    [[ -e ".rodentrc" ]] && {
      break
    }
    cd ..
  done
  localdir="$PWD"
  popd
}

for rodentrc in $RODENT_HOME/.rodentrc $localdir/.rodentrc
do
  [[ -f "$rodentrc" ]] && {
    . "$rodentrc" || {
      echo "an error occured, could not source $rodentrc"
      exit 1
    }
  }
done

[[ -z "$RODENT_ENV" ]] || {
  rodent_env="_$RODENT_ENV"
}

# rodent variables expansion
gover_set="gover$rodent_env"
gobin_set="gobin$rodent_env"
gopath_set="gopath$rodent_env"
godeps_set="godeps$rodent_env"

gover="${RODENT_GOLANG_VERSION:-${!gover_set}}"
[[ -z "$gover" ]] && {
  echo "no version of go was set"
  echo "you can set a go version by executing \"rodent set -g go<ver>\""
  exit 1
}

goroot="$RODENT_GOROOT_TOP/$gover"
[[ -x "$goroot/bin/$prog" ]] || {
  echo "the version you wish to use does not exists or is broken"
  echo "you can verify your installation by executing \"rodent versions\""
  exit 1
}
export GOROOT="$goroot"

[[ -z $gopath_set || -z $godeps_set ]] || {
  GOPATH=${!godeps_set}:${!gopath_set}:$GOPATH
}

export GOPATH

GOBIN=${GOBIN:-${!gobin_set}}
export GOBIN

export PATH="$goroot/bin:$PATH"
exec "$prog" "$@"
